#!/usr/bin/env python3
"""Build site/index.html and site/herd.html.

Why this exists rather than a framework: the site is two pages, and the only
things that actually hurt were the chrome being copied into both and the eight
guide steps being hand-written HTML that the homepage cards had to be kept in
step with by hand — which they twice were not. Both are fixed here, in a script
with no dependencies, so the Pages deploy stays "upload a folder" and there is
no second ecosystem to keep alive beside a Swift app.

    python3 site/_src/build.py            # write the pages
    python3 site/_src/build.py --check    # fail if they are out of date

`--check` is the one that matters in CI: it rebuilds into memory and compares,
so a page edited directly instead of through here cannot land unnoticed.
"""
from __future__ import annotations

import pathlib
import re
import sys

SRC = pathlib.Path(__file__).parent
OUT = SRC.parent
sys.path.insert(0, str(SRC))
from steps import STEPS  # noqa: E402

BANNER = ("<!-- Generated by site/_src/build.py — do not edit this file.\n"
          "     Content lives in site/_src/. Run the script after changing it. -->\n")


def partial(name: str) -> str:
    return SRC.joinpath("partials", name + ".html").read_text()


def fill(text: str, **slots: str) -> str:
    for key, value in slots.items():
        text = text.replace("{{%s}}" % key, value)
    left = re.findall(r"\{\{(\w+)\}\}", text)
    if left:
        sys.exit(f"build: unfilled slots {sorted(set(left))}")
    return text


# --------------------------------------------------------------- the guide
def render_steps() -> str:
    out = []
    for step in STEPS:
        tool = step["tool"]
        out.append(
            f'  <li class="step" id="{step["id"]}">\n'
            f'    <div class="step-n">{step["n"]}</div>\n'
            f'    <div class="step-body">\n'
            f'      <h2>{step["heading"]}</h2>\n'
            f'      <p class="what">{step["what"]}</p>\n'
            f'{step["figure"]}\n'
            f'      <a class="tool" href="{tool["url"]}">\n'
            f'        <span class="tool-name">{tool["name"]}</span>\n'
            f'        <span class="tool-note">{tool["note"]}</span>\n'
            f'        <span class="tool-go">{tool["go"]}</span>\n'
            f'      </a>\n'
            f'{step["body"]}\n'
            f'    </div>\n'
            f'  </li>\n\n'
        )
    return "".join(out)


# ------------------------------------------------------------ the homepage
def render_cards() -> str:
    out = []
    for step in STEPS:
        card = step["card"]
        # the tool name and the anchor come from the step, never from the card,
        # so the two pages cannot disagree about what a thing is called
        out.append(
            f'      <div><h3>{card["heading"]}</h3>\n'
            f'        <p>{card["text"]}</p>\n'
            f'        <a class="card-tool" href="herd.html#{step["id"]}">{card["tool"]}</a></div>'
        )
    return "\n".join(out)


PAGES = {
    "index.html": dict(
        page="index.page",
        title="Little Herd — a menu-bar monitor for all your machines",
        description=("Little Herd watches your Mac, your other Macs, your Linux boxes and "
                     "your NAS from the menu bar — CPU, memory, disk, and which AI agents "
                     "are running where."),
        og_title="Little Herd",
        og_description=("Put your herd to work. See the load across your machines and the "
                        "AI sessions running on them, from the menu bar."),
        top_class="",
        lockup=('  <img src="images/icon.png" alt="">\n'
                '  <svg class="wordmark" viewBox="0 0 915 147" role="img" aria-label="Little Herd">'
                '<use href="wordmark.svg#wordmark"/></svg>'),
        nav=('<a href="herd.html">Start a herd</a> '
             '<a href="https://github.com/malpern/little-herd">GitHub</a>'),
        # anything after </footer> has to be declared: the body slice stops
        # there, and the first build silently dropped this, which killed all
        # three live panels while every page still rendered perfectly
        scripts='<script src="demo.js"></script>',
        footer_links=(
            '    <a href="herd.html">Start a herd</a>\n'
            '    <a href="https://github.com/malpern/little-herd">Source on GitHub</a>\n'
            '    <a href="https://github.com/malpern/little-herd/releases">Release notes</a>\n'
            '    <a href="https://github.com/malpern/little-herd/blob/main/LICENSE.md">Licence</a>'),
    ),
    "herd.html": dict(
        page="herd.page",
        title="Start a herd — Little Herd",
        description=("Eight things you can do once your computers are a herd: reach any of "
                     "them from anywhere, get on with one command, find your tools already "
                     "there, start work and walk away, use another machine’s screen, and run "
                     "several agents at once."),
        og_title="Start a herd",
        og_description="Eight things that turn a pile of computers into a herd.",
        top_class=" top-solid",
        lockup=('  <a class="lockup" href="./">\n'
                '    <img src="images/icon.png" alt="">\n'
                '    <svg class="wordmark" viewBox="0 0 915 147" role="img" aria-label="Little Herd">'
                '<use href="wordmark.svg#wordmark"/></svg>\n'
                '  </a>'),
        nav=('<a href="./">The app</a> '
             '<a href="https://github.com/malpern/little-herd">GitHub</a>'),
        scripts='',
        footer_links=(
            '    <a href="./">Little Herd</a>\n'
            '    <a href="https://github.com/malpern/little-herd">Source on GitHub</a>'),
    ),
}


def render(name: str) -> str:
    spec = dict(PAGES[name])
    body = SRC.joinpath(spec.pop("page")).read_text()
    body = fill(body, steps=render_steps(), cards=render_cards()) if "{{" in body else body
    head = fill(partial("head"), **{k: spec[k] for k in
                                    ("title", "description", "og_title", "og_description")})
    header = fill(partial("header"), **{k: spec[k] for k in ("top_class", "lockup", "nav")})
    footer = fill(partial("footer"), footer_links=spec["footer_links"])
    tail = ("\n" + spec["scripts"] + "\n") if spec["scripts"] else "\n"
    return BANNER + head + "\n" + header + "\n" + body + footer + tail + "</body>\n</html>\n"


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for name in PAGES:
        built = render(name)
        target = OUT / name
        if check:
            if not target.exists() or target.read_text() != built:
                stale.append(name)
        else:
            target.write_text(built)
            print(f"wrote {name} ({len(built):,} bytes)")
    if check:
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run: python3 site/_src/build.py")
            return 1
        print("pages are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
