#!/usr/bin/env python3
"""Build site/index.html and site/herd.html.

Why this exists rather than a framework: the site is two pages, and the only
things that actually hurt were the chrome being copied into both and the nine
guide steps being hand-written HTML that the homepage cards had to be kept in
step with by hand — which they twice were not. Both are fixed here, in a script
with no dependencies, so the Pages deploy stays "upload a folder" and there is
no second ecosystem to keep alive beside a Swift app.

    python3 site/_src/build.py            # write the pages
    python3 site/_src/build.py --check    # fail if they are out of date

`--check` is the one that matters in CI: it rebuilds into memory and compares,
so a page edited directly instead of through here cannot land unnoticed.
"""
from __future__ import annotations

import html as _html
import pathlib
import urllib.parse
import re
import sys

SRC = pathlib.Path(__file__).parent
OUT = SRC.parent
sys.path.insert(0, str(SRC))
from steps import STEPS  # noqa: E402

BANNER = ("<!-- Generated by site/_src/build.py — do not edit this file.\n"
          "     Content lives in site/_src/. Run the script after changing it. -->\n")


# ------------------------------------------------------------- highlighting
# Done here, at build time, rather than by shipping a highlighter: the site has
# no JavaScript dependencies and the Artifact preview runs under a CSP that
# blocks external scripts, so a runtime highlighter would cost a request on the
# site and simply not run in the preview. Two languages appear in this guide,
# which is small enough to tokenise honestly.

SSH_DIRECTIVES = {
    "host", "hostname", "user", "port", "identityfile", "include", "match",
    "identitiesonly", "forwardagent", "proxyjump", "serveraliveinterval",
    "stricthostkeychecking", "userknownhostsfile", "addkeystoagent",
}


def _tok(cls: str, text: str) -> str:
    return f'<span class="t-{cls}">{_html.escape(text)}</span>'


def _shell_line(line: str) -> str:
    """A command line: comment, command, flags, paths, everything else."""
    code, sep, comment = line.partition("#")
    out = []
    first = True
    for part in re.split(r"(\s+)", code):
        if not part:
            continue
        if part.isspace():
            out.append(part)
        elif first and part.isidentifier() or (first and re.fullmatch(r"[\w./-]+", part)):
            out.append(_tok("cmd", part)); first = False
        elif part.startswith("-"):
            out.append(_tok("flag", part))
        elif "/" in part or part.startswith("~"):
            out.append(_tok("path", part))
        else:
            out.append(_html.escape(part))
            first = False
    if sep:
        out.append(_tok("cmt", sep + comment))
    return "".join(out)


def _ssh_line(line: str) -> str:
    """A config line: the directive, then its value."""
    m = re.match(r"(\s*)([A-Za-z]+)(\s+)(.*)$", line)
    if not m or m.group(2).lower() not in SSH_DIRECTIVES:
        return _html.escape(line)
    indent, key, gap, value = m.groups()
    return indent + _tok("key", key) + gap + _tok("val", value)


def highlight(code: str) -> str:
    text = _html.unescape(code)
    lines = text.split("\n")
    is_ssh = any(re.match(r"\s*(Host|Match|Include)\s+\S", l) for l in lines)
    render = _ssh_line if is_ssh else _shell_line
    return "\n".join(render(l) if l.strip() else "" for l in lines)


def highlight_blocks(fragment: str) -> str:
    return re.sub(r"<pre><code>(.*?)</code></pre>",
                  lambda m: f"<pre><code>{highlight(m.group(1))}</code></pre>",
                  fragment, flags=re.S)


def partial(name: str) -> str:
    return SRC.joinpath("partials", name + ".html").read_text()


def logo(name: str) -> str:
    """The tool's mark, inlined so it takes currentColor and costs no request.

    Three are real: Tailscale, Homebrew and tmux, from Simple Icons under CC0,
    with the hardcoded fill stripped. The rest are drawn to match, because
    OpenSSH has no mark, Apple's would imply an endorsement nobody gave, and
    Herdr's is Apache-2.0 -- which grants no trademark rights -- over a solid
    background that would not theme.
    """
    svg = SRC.joinpath("logos", name + ".svg").read_text().strip()
    return svg.replace("<svg ", '<svg class="tool-logo" ', 1)


def fill(text: str, **slots: str) -> str:
    for key, value in slots.items():
        text = text.replace("{{%s}}" % key, value)
    left = re.findall(r"\{\{(\w+)\}\}", text)
    if left:
        sys.exit(f"build: unfilled slots {sorted(set(left))}")
    return text


# --------------------------------------------------------------- the guide
# Nine steps in one column read as nine identical blocks. They are really
# three acts, and saying so gives the page a shape a reader can hold.
ACTS = [
    ("Get access", "Reaching every machine, and making each one worth arriving at.",
     ("reach", "connect", "tools")),
    ("Put them to work", "Running things you can walk away from, and seeing what a shell cannot show you.",
     ("detach", "screen", "control", "agents")),
    ("Keep it alive", "The two that decide whether a herd survives being left alone.",
     ("backup", "alerts")),
]


def render_toc() -> str:
    """A contents list. People arrive here from a search for one step."""
    by_id = {s["id"]: s for s in STEPS}
    groups = []
    for title, _, ids in ACTS:
        items = "".join(
            f'        <li><a href="#{i}"><b>{by_id[i]["n"]}</b>{by_id[i]["heading"]}</a></li>\n'
            for i in ids)
        groups.append(f'      <div>\n        <h3>{title}</h3>\n        <ol>\n{items}        </ol>\n      </div>\n')
    return ('  <nav class="toc wrap" aria-label="The nine steps">\n'
            + "".join(groups) + '  </nav>\n')


def render_rail() -> str:
    """A sticky strip of the nine numbers, for the long scroll.

    It ships `hidden` and is revealed by guide.js once the contents list above
    has scrolled away, then hides again past the last step. Sticky-in-flow was
    tried first: it needed no script to appear, but at rest it sat immediately
    under the contents as a second, terser copy of the same nine items, and
    looked like a mistake. Being script-only is the right trade here -- the
    contents list is the navigation that survives scripting being off, and this
    is an affordance for the twelve thousand pixels that follow it.

    The compressed form is numbers, not headings. Eight headings the length of
    "Start something on another machine and walk away" cannot be a bar at any
    width. What the numbers lose is the grouping, so the current act's name is
    carried on the left -- it changes three times over the whole page instead
    of eight, which is the difference between a label and a flicker.
    """
    by_id = {s["id"]: s for s in STEPS}
    groups = []
    for title, _, ids in ACTS:
        items = "".join(
            f'<li><a href="#{i}" title="{by_id[i]["heading"]}">'
            f'<span class="sr">{by_id[i]["n"]}. {by_id[i]["heading"]}</span>'
            f'<span aria-hidden="true">{by_id[i]["n"]}</span></a></li>'
            for i in ids)
        groups.append(f'<ol data-act="{title}">{items}</ol>')
    return ('  <nav class="rail" aria-label="The nine steps" hidden>\n'
            '    <div class="rail-in wrap">\n'
            '      <span class="rail-act" aria-hidden="true">Get access</span>\n'
            '      <div class="rail-nums">' + "".join(groups) + '</div>\n'
            '    </div>\n'
            '  </nav>\n')


def shot(step: dict) -> str:
    """A real screenshot of the tool, after the prose that explains it.

    Every one was taken in a disposable lab VM with an invented hostname, so
    none of them has anything real in it to redact. They sit last in the step
    because they answer "is this what I should be seeing" -- a question a
    reader only has once they have run the thing.
    """
    if not step.get("shot"):
        return ""
    img, caption = step["shot"]
    return (f'      <figure class="shot-fig">\n'
            f'        <img src="images/guide/{img}" alt="{caption}" loading="lazy">\n'
            f'        <figcaption>{caption}</figcaption>\n'
            f'      </figure>\n')


def mark() -> str:
    """OpenAI's mark, from the Wikimedia SVG: one petal rotated six times.

    Their brand guidelines permit third-party referential use, on two
    conditions this meets -- it must not imply endorsement, and it must not be
    more prominent than our own mark. It is a 17px glyph inside a button, on a
    page led by the Little Herd wordmark, and the button says what it does
    rather than claiming a relationship.
    """
    svg = SRC.joinpath("logos", "openai.svg").read_text().strip()
    return svg.replace("<svg ", '<svg class="ask-mark" ', 1)


def video(step: dict) -> str:
    """One creator's video, where a good one exists.

    Every step has one now, from whoever made the best one rather than from a
    shortlist of channels. Every candidate was checked against YouTube's oembed for its real title and channel rather than
    trusted from a search result, and two that looked perfect were dropped once
    read: "The Perfect Home DNS Flow" is about DNSimple and auto-SSL rather
    than Pi-hole, and "Stop Using Tailscale" argues against the tool the step
    is recommending. A link that turns out to be neither is worse than no link.
    """
    if not step.get("video"):
        return ""
    who, title, vid = step["video"]
    return (
        f'      <a class="vid" href="https://www.youtube.com/watch?v={vid}"\n'
        f'         target="_blank" rel="noopener">\n'
        f'        <span class="vid-play" aria-hidden="true"></span>\n'
        f'        <span class="vid-txt"><b>{title}</b><i>{who} on YouTube</i></span>\n'
        f'      </a>\n'
    )


def ask(step: dict) -> str:
    """A prefilled ChatGPT prompt for the tool this step introduces.

    `?q=` is not documented by OpenAI but is long-established and widely used.
    The prompts are kept a few hundred characters because a very long query
    string risks being cut by a WAF along the way.

    The button says "Ask ChatGPT" in words and carries a drawn glyph rather
    than OpenAI's mark: Simple Icons no longer carries that logo, which usually
    means it was removed at the owner's request, and naming a product you are
    pointing someone at is fine where reproducing its logo may not be.
    """
    if not step.get("ask"):
        return ""
    label, prompt = step["ask"]
    href = "https://chatgpt.com/?q=" + urllib.parse.quote(prompt, safe="")
    return (
        f'      <div class="ask">\n'
        f'        <p>Want to go further than this page does? Ask ChatGPT to walk you\n'
        f'          through installing and using <b>{label}</b> on your own machines.</p>\n'
        f'        <a class="ask-btn" href="{href}" target="_blank" rel="noopener">\n'
        f'          {mark()}\n'
        f'          Ask ChatGPT\n'
        f'        </a>\n'
        f'      </div>\n'
    )


def render_step(step: dict) -> str:
    """One column, in reading order: what you can do, then a picture of it,
    then the tool, then how, then the trap.

    This was briefly two columns, with the figure and tool card in a sidebar,
    to use the width that a 40rem measure leaves empty at desktop. That was
    optimising for the wrong thing. A guide is read rather than scanned, and a
    single column means the reader never has to decide where to look next; the
    empty right-hand side is the cost of a comfortable measure, not a defect.
    """
    tool = step["tool"]
    return (
        f'  <li class="step" id="{step["id"]}">\n'
        f'    <div class="step-n">{step["n"]}</div>\n'
        f'    <div class="step-body">\n'
        f'      <h2>{step["heading"]}</h2>\n'
        f'      <p class="what">{step["what"]}</p>\n'
        f'{step["figure"]}\n'
        f'      <a class="tool" href="{tool["url"]}">\n'
        f'        {logo(step["logo"])}\n'
        f'        <span class="tool-name">{tool["name"]}</span>\n'
        f'        <span class="tool-note">{tool["note"]}</span>\n'
        f'        <span class="tool-go">{tool["go"]}</span>\n'
        f'      </a>\n'
        f'{highlight_blocks(step["body"])}\n'
        f'{video(step)}'
        f'{shot(step)}'
        f'{ask(step)}'
        f'    </div>\n'
        f'  </li>\n\n'
    )


def render_steps() -> str:
    by_id = {s["id"]: s for s in STEPS}
    seen = set()
    out = [render_toc(), render_rail()]
    for n, (title, blurb, ids) in enumerate(ACTS, 1):
        out.append(f'  <div class="act wrap">\n'
                   f'    <span class="act-n">Act {n}</span>\n'
                   f'    <h2>{title}</h2>\n'
                   f'    <p>{blurb}</p>\n'
                   f'  </div>\n\n'
                   f'  <ol class="steps wrap">\n')
        for i in ids:
            out.append(render_step(by_id[i]))
            seen.add(i)
        out.append('  </ol>\n\n')
    missing = [s["id"] for s in STEPS if s["id"] not in seen]
    if missing:
        sys.exit(f"build: steps missing from ACTS: {missing}")
    return "".join(out)


# ------------------------------------------------------------ the homepage
def render_cards() -> str:
    out = []
    for step in STEPS:
        card = step["card"]
        # the tool name and the anchor come from the step, never from the card,
        # so the two pages cannot disagree about what a thing is called
        out.append(
            f'      <div><h3>{card["heading"]}</h3>\n'
            f'        <p>{card["text"]}</p>\n'
            f'        <a class="card-tool" href="herd.html#{step["id"]}">{card["tool"]}</a></div>'
        )
    return "\n".join(out)


PAGES = {
    "index.html": dict(
        page="index.page",
        title="Little Herd — a menu-bar monitor for all your machines",
        description=("Little Herd watches your Mac, your other Macs, your Linux boxes and "
                     "your NAS from the menu bar — CPU, memory, disk, and which AI agents "
                     "are running where."),
        og_title="Little Herd",
        og_description=("Put your herd to work. See the load across your machines and the "
                        "AI sessions running on them, from the menu bar."),
        top_class="",
        lockup=('  <img src="images/icon.png" alt="">\n'
                '  <svg class="wordmark" viewBox="0 0 915 147" role="img" aria-label="Little Herd">'
                '<use href="wordmark.svg#wordmark"/></svg>'),
        nav=('<a href="herd.html">Start a herd</a> '
             '<a href="https://github.com/malpern/little-herd">GitHub</a>'),
        # anything after </footer> has to be declared: the body slice stops
        # there, and the first build silently dropped this, which killed all
        # three live panels while every page still rendered perfectly
        scripts='<script src="demo.js"></script>',
        footer_links=(
            '    <a href="herd.html">Start a herd</a>\n'
            '    <a href="https://github.com/malpern/little-herd">Source on GitHub</a>\n'
            '    <a href="https://github.com/malpern/little-herd/releases">Release notes</a>\n'
            '    <a href="https://github.com/malpern/little-herd/blob/main/LICENSE.md">Licence</a>'),
    ),
    "herd.html": dict(
        page="herd.page",
        title="Start a herd — Little Herd",
        description=("Eight things you can do once your computers are a herd: reach any of "
                     "them from anywhere, get on with one command, find your tools already "
                     "there, start work and walk away, use another machine’s screen, and run "
                     "several agents at once."),
        og_title="Start a herd",
        og_description="Eight things that turn a pile of computers into a herd.",
        top_class=" top-solid",
        lockup=('  <a class="lockup" href="./">\n'
                '    <img src="images/icon.png" alt="">\n'
                '    <svg class="wordmark" viewBox="0 0 915 147" role="img" aria-label="Little Herd">'
                '<use href="wordmark.svg#wordmark"/></svg>\n'
                '  </a>'),
        nav=('<a href="./">The app</a> '
             '<a href="https://github.com/malpern/little-herd">GitHub</a>'),
        scripts='<script src="guide.js"></script>',
        footer_links=(
            '    <a href="./">Little Herd</a>\n'
            '    <a href="https://github.com/malpern/little-herd">Source on GitHub</a>'),
    ),
}


def render(name: str) -> str:
    spec = dict(PAGES[name])
    body = SRC.joinpath(spec.pop("page")).read_text()
    body = fill(body, steps=render_steps(), cards=render_cards()) if "{{" in body else body
    head = fill(partial("head"), **{k: spec[k] for k in
                                    ("title", "description", "og_title", "og_description")})
    header = fill(partial("header"), **{k: spec[k] for k in ("top_class", "lockup", "nav")})
    footer = fill(partial("footer"), footer_links=spec["footer_links"])
    tail = ("\n" + spec["scripts"] + "\n") if spec["scripts"] else "\n"
    return BANNER + head + "\n" + header + "\n" + body + footer + tail + "</body>\n</html>\n"


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for name in PAGES:
        built = render(name)
        target = OUT / name
        if check:
            if not target.exists() or target.read_text() != built:
                stale.append(name)
        else:
            target.write_text(built)
            print(f"wrote {name} ({len(built):,} bytes)")
    if check:
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run: python3 site/_src/build.py")
            return 1
        print("pages are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
